---
- name: Create ansible user and grant admin access
  hosts: all
  gather_facts: false
  no_warnings: true

  tasks:
    - name: Ensure user Ansible is present
      win_user:
        name: ansible
        password: HavePassword2023!
        state: present
        groups:
          - Administrators
