---
- name: Update and reboot Windows Server 2019
  hosts: all
  gather_facts: false

  tasks:
    - name: Check for pending updates
      win_updates:
        category_names: SecurityUpdates
        state: searched
      register: win_updates_result

    - name: Install updates if available
      win_updates:
        category_names: SecurityUpdates
        state: installed
      when: win_updates_result.updates | length > 0

    - name: Reboot the server
      win_reboot:
        reboot_timeout: 600
      when: win_updates_result.updates | length > 0
