---
- name: Update and Reboot RHEL Server
  hosts: all

  tasks:
  - name: Install Package Updates
    yum:
      name: "*"
      state: latest
      disable_gpg_check: yes
      exclude: "{{ exclude }}"
      update_cache: True
    ignore_errors: True
    register: yum_update
    
  - name: Check for required Reboot
    command: needs-restarting -r
    ignore_errors: True
    register: needs_reboot
        
  - name: Set required Reboot to rest
    set_fact:
      needs_reboot:
        rc: "{% if yum_update.changed %}1{% else %}0{% endif %}"
    when: needs_reboot.rc is not defined

  - name: Reboot and wait for start
    reboot:
      msg: "Reboot triggered by Ansible"
      pre_reboot_delay: 60
      post_reboot_delay: 120
      reboot_timeout: '{{ host_timeout_ssh | default(300) }}'
