---
- name: Update and Reboot RHEL Server
  hosts: all

  tasks:
    - name: Clean cache and refresh repositories
      shell:
        cmd: |
          yum clean all
          subscription-manager refresh

    - name: Update packages
      yum:
        name: '*'
        state: latest
        disable_gpg_check: yes
      register: yum_output

    - name: Reboot if kernel package has been updated
      command: shutdown -r now
      when: "'kernel' in yum_output.stdout_lines"
