---
- name: Create ansible user and grant sudo access
  hosts: all
  become: yes

  tasks:
    - name: Create ansible user
      user:
        name: ansible
        password: "{{ 'have' | password_hash('sha512', 'mysecretsalt') }}"
        createhome: yes

    - name: Create ansible sudoers file
      copy:
        dest: /etc/sudoers.d/ansible
        content: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'

    - name: Create SSH directory for Ansible user
      file:
        path: "/home/ansible/.ssh"
        state: directory
        mode: "0700"
        owner: ansible
        group: ansible

    - name: Copy local RSA public key to remote host
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present
