---
- name: Create ansible user and grant sudo access
  hosts: all
  become: yes

  tasks:
    - name: Create ansible user
      user:
        name: ansible
        password: "{{ 'ansible' | password_hash('sha512', 'mysecretsalt') }}"
        createhome: yes

    - name: Create ansible sudoers file
      copy:
        dest: /etc/sudoers.d/ansible
        content: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'

    - name: Create SSH directory for Ansible user
      file:
        path: "/home/ansible/.ssh"
        state: directory
        mode: "0700"
        owner: ansible
        group: ansible

    - name: Add Ansible user's public key to authorized_keys
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present

    - name: Install python3.11 and python3.11-pip packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3.11
        - python3.11-pip

    - name: Install pexpect module using python3.11 pip
      command: python3.11 -m pip install pexpect

    - name: Install pymysql module using python3.11 pip
      command: python3.11 -m pip install pymysql
