---
- name: Create ansible user and grant sudo access
  hosts: all

  tasks:
    - name: Create ansible user
      user:
        name: ansible
        password: "{{ 'have' | password_hash('sha512', 'mysecretsalt') }}"
        createhome: yes

    - name: Create ansible sudoers file
      copy:
        dest: /etc/sudoers.d/ansible
        content: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'

    - name: Create SSH directory for Ansible user
      file:
        path: "/home/ansible/.ssh"
        state: directory
        mode: "0700"
        owner: ansible
        group: ansible

    - name: Copy RSA public key
      ansible.builtin.synchronize:
        src: "/home/ansible/.ssh/id_rsa.pub"
        dest: "/home/ansible/.ssh/id_rsa_ansible.pub"
        rsync_opts:
          - "--chown=ansible:ansible"
      delegate to: ansible

    - name: Add RSA public key to authorized_keys
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa_ansible.pub') }}"
        state: present
