---
- name: Update the system
  hosts: all
  gather_facts: false
  PYTHONWARNINGS: ignore


  tasks:
    - name: Perform system update
      dnf:
        name: '*'
        disable_gpg_check: true
        update_cache: true
        state: latest
      register: update_package_result

    - name: Reboot the system if packages are updated
      reboot:
        reboot_timeout: 300
        msg: "Reboot initiated due to package update"
      when: update_package_result.changed

    - name: Wait for the system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Autoremove unneeded packages installed
      dnf:
        autoremove: yes

    - name: Clean dnf cache
      command: dnf clean all 
