---
- name: Update the system
  hosts: all

  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest
        update_cache: yes
      register: package_update_result

    - name: Perform system update
      package:
        name: '*'
        state: latest
      register: system_update_result
      when: package_update_result.changed

    - name: Check if kernel packages are modified
      dnf:
        list: kernel*
      register: kernel_package_result
      changed_when: kernel_package_result.changed | default(false)

    - name: Reboot the system if kernel packages are modified
      reboot:
        reboot_timeout: 300
        msg: "Reboot initiated due to kernel package modification"
      when: kernel_package_result.changed | default(false)

    - name: Wait for the system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300
