---
- name: Update the system
  hosts: all

  tasks:
    - name: Perform system update
      dnf:
        name: '*'
        disable_gpg_check: true
        state: latest
      register: update_package_result

    - name: Debug update_package_result.changed
      debug:
        var: update_package_result.changed

    - name: Reboot the system if kernel packages are modified
      reboot:
        reboot_timeout: 300
        msg: "Reboot initiated due to kernel package modification"
      when: "'kernel-*' in update_package_result"

    - name: Wait for the system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Autoremove unneeded packages installed as dependencies
      dnf:
        autoremove: yes
