---
- name: Update the system
  hosts: all

  tasks:
    - name: Perform system update
      dnf:
        name: '*'
        disable_gpg_check: true
        state: latest
      register: update_package_result

    - name: Check for modified kernel packages
      set_fact:
        kernel_packages_modified: "{{ update_package_result.results | selectattr('item') | selectattr('item.key', 'match', '^kernel.*') | list }}"
      when: update_package_result.changed

    - name: Reboot the system if kernel packages are modified
      reboot:
        reboot_timeout: 300
        msg: "Reboot initiated due to kernel package modification"
      when: kernel_packages_modified

    - name: Wait for the system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Autoremove unneeded packages installed as dependencies
      dnf:
        autoremove: yes
