---
- name: Update the system
  hosts: all

  tasks:
    - name: Perform system update
      dnf:
        name: '*'
        disable_gpg_check: true
        allowerasing: true
        state: latest

    - name: Check if kernel packages are modified
      dnf:
        list: kernel*
      register: kernel_package_result
      changed_when: kernel_package_result.changed | default(true)

    - name: Reboot the system if kernel packages are modified
      reboot:
        reboot_timeout: 300
        msg: "Reboot initiated due to kernel package modification"
      when: kernel_package_result.changed | default(true)

    - name: Wait for the system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Autoremove unneeded packages installed as dependencies
      dnf:
        autoremove: yes
